In [ ]:
# get data from grouplens (movielens data)
!wget https://files.grouplens.org/datasets/movielens/ml-100k.zip

In [ ]:
!unzip ml-100k.zip

In [5]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
# Define file paths
ratings_file = '/content/ml-100k/u.data'
movies_file = '/content/ml-100k/u.item'

# Load ratings data
ratings_columns = ['user_id', 'movie_id', 'rating', 'timestamp']
movies_ratings_df = pd.read_csv(ratings_file, sep='\t', names=ratings_columns)

# Load movies data
movies_columns = ['movie_id', 'movie_title', 'release_date', 'video_release_date', 'IMDb_URL', 'unknown',
                  'Action', 'Adventure', 'Animation', 'Children', 'Comedy', 'Crime', 'Documentary', 'Drama',
                  'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller',
                  'War', 'Western']
movies_df = pd.read_csv(movies_file, sep='|', names=movies_columns, encoding='latin-1')

In [12]:
movies_ratings_df.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [15]:
# Merge ratings and movie data
movies_ratings_df = pd.merge(movies_ratings_df, movies_df[['movie_id', 'movie_title']], on='movie_id')
movies_ratings_df.drop(['timestamp'], axis=1, inplace=True)
movies_ratings_df.head()

   user_id  movie_id  rating                 movie_title
0      196       242       3                Kolya (1996)
1      186       302       3    L.A. Confidential (1997)
2       22       377       1         Heavyweights (1994)
3      244        51       2  Legends of the Fall (1994)
4      166       346       1         Jackie Brown (1997)

In [17]:
# Create user-item matrix for the filtered popular movies
user_item_matrix = movies_ratings_df.pivot_table(index='user_id', columns='movie_title', values='rating')

user_item_matrix.head()

movie_title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,2.0,5.0,NaN,NaN,3.0,4.0,NaN,NaN,...,NaN,NaN,NaN,5.0,3.0,NaN,NaN,NaN,4.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,2.0,NaN,NaN,NaN,NaN,4.0,NaN,NaN,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,4.0,NaN

In [22]:
# Fill missing ratings with 0
user_item_matrix.fillna(0, inplace=True)

# Compute user similarity matrix using cosine similarity (user-user matrix)
similarity_matrix = cosine_similarity(user_item_matrix)

# Convert to DataFrame for easier handling
similarity_df = pd.DataFrame(similarity_matrix, index=user_item_matrix.index, columns=user_item_matrix.index)

similarity_df.head()

user_id,1,2,3,4,5,6,7,8,9,10,...,934,935,936,937,938,939,940,941,942,943
user_id,,,,,,,,,,,,,,,,,,,,,
1,1.000000,0.168937,0.048388,0.064561,0.379670,0.429682,0.443097,0.320079,0.078385,0.377733,...,0.372213,0.119860,0.269860,0.193343,0.197949,0.118722,0.315064,0.149086,0.181612,0.399432
2,0.168937,1.000000,0.113393,0.179694,0.073623,0.242106,0.108604,0.104257,0.162470,0.161273,...,0.147095,0.310661,0.363328,0.410725,0.322713,0.231096,0.228793,0.162911,0.175273,0.106732
3,0.048388,0.113393,1.000000,0.349781,0.021592,0.074018,0.067423,0.084419,0.062039,0.066217,...,0.033885,0.043453,0.167140,0.071288,0.126278,0.026758,0.164539,0.102899,0.136757,0.026990
4,0.064561,0.179694,0.349781,1.000000,0.031804,0.068431,0.091507,0.188060,0.101284,0.060859,...,0.054615,0.036784,0.133619,0.196561,0.146058,0.030202,0.196858,0.152041,0.171538,0.058752
5,0.379670,0.073623,0.021592,0.031804,1.000000,0.238636,0.374733,0.248930,0.056847,0.201427,...,0.340183,0.080580,0.095284,0.081053,0.148607,0.071612,0.239955,0.139595,0.153799,0.313941

In [25]:
# Function to recommend movies for a user (only from popular movies)
def recommend_movies_colab_user(user_id, n_recommendations=5, similarity_threshold=0.5):
    # Get the list of similar users
    similar_users = similarity_df[user_id].sort_values(ascending=False)
    similar_users = similar_users[similar_users > similarity_threshold]

    # Get watched movies for the user
    user_movies = user_item_matrix.loc[user_id]
    watched_movies = user_movies[user_movies > 0].index.tolist()

    # Get movies watched by similar users
    similar_user_ratings = user_item_matrix.loc[similar_users.index]
    similar_user_ratings = similar_user_ratings.mean().sort_values(ascending=False)

    # Recommend movies not yet watched by the user
    recommendations = [movie for movie in similar_user_ratings.index if movie not in watched_movies]

    return recommendations[:n_recommendations]

In [42]:
# Example: Recommend movies for a user (example for user with ID 5)
collaborative_recommendations_user = recommend_movies_colab_user(user_id=1, n_recommendations=5)

collaborative_recommendations_user

["Schindler's List (1993)",
 "One Flew Over the Cuckoo's Nest (1975)",
 'E.T. the Extra-Terrestrial (1982)',
 'Casablanca (1942)',
 "It's a Wonderful Life (1946)"]

In [28]:
# Get the titles of the movies User 10 has watched
watched_movies_user_1 = user_item_matrix.loc[1]
watched_movies_user_1 = watched_movies_user_1[watched_movies_user_1 > 0].index.tolist()

# Display the watched movies
print("Movies watched by User 1: ", watched_movies_user_1)

Movies watched by User 1:  ['101 Dalmatians (1996)', '12 Angry Men (1957)', '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)', 'Abyss, The (1989)', 'Ace Ventura: Pet Detective (1994)', 'Air Bud (1997)', 'Akira (1988)', 'Aladdin (1992)', 'Alien (1979)', 'Aliens (1986)', 'All Dogs Go to Heaven 2 (1996)', 'Amadeus (1984)', 'Angels and Insects (1995)', "Antonia's Line (1995)", 'Apocalypse Now (1979)', 'Apollo 13 (1995)', 'Aristocats, The (1970)', 'Army of Darkness (1993)', 'Austin Powers: International Man of Mystery (1997)', 'Babe (1995)', 'Back to the Future (1985)', 'Bad Boys (1995)', 'Basic Instinct (1992)', 'Batman & Robin (1997)', 'Batman Forever (1995)', 'Batman Returns (1992)', 'Beavis and Butt-head Do America (1996)', 'Bedknobs and Broomsticks (1971)', 'Belle de jour (1967)', 'Big Night (1996)', 'Billy Madison (1995)', 'Birdcage, The (1996)', 'Blade Runner (1982)', 'Blues Brothers, The (1980)', 'Bound (1996)', "Bram Stoker's Dracula (1992)", 'Braveheart (1995)', 'Brazil (1985)', "Breakfast at Tiffany's (1961)", 'Breaking the Waves (1996)', 'Bridge on the River Kwai, The (1957)', 'Brother Minister: The Assassination of Malcolm X (1994)', 'Brothers McMullen, The (1995)', 'Cable Guy, The (1996)', 'Cape Fear (1991)', "Carlito's Way (1993)", 'Chasing Amy (1997)', 'Cinema Paradiso (1988)', 'Citizen Kane (1941)', 'Citizen Ruth (1996)', 'Clerks (1994)', 'Clockwork Orange, A (1971)', 'Cold Comfort Farm (1995)', 'Contact (1997)', 'Copycat (1995)', 'Crimson Tide (1995)', 'Crow, The (1994)', 'Crumb (1994)', 'Cyrano de Bergerac (1990)', 'D3: The Mighty Ducks (1996)', 'Dances with Wolves (1990)', 'Dead Man Walking (1995)', 'Dead Poets Society (1989)', 'Delicatessen (1991)', 'Desperado (1995)', "Devil's Own, The (1997)", 'Diabolique (1996)', 'Die Hard (1988)', 'Die Hard 2 (1990)', 'Dirty Dancing (1987)', 'Disclosure (1994)', 'Dolores Claiborne (1994)', 'Doom Generation, The (1995)', 'Eat Drink Man Woman (1994)', 'Ed Wood (1994)', 'Empire Strikes Back, The (1980)', 'Event Horizon (1997)', 'Evil Dead II (1987)', 'Exotica (1994)', 'Fargo (1996)', 'Faster Pussycat! Kill! Kill! (1965)', 'Field of Dreams (1989)', 'Fifth Element, The (1997)', 'Firm, The (1993)', 'Fish Called Wanda, A (1988)', 'Flipper (1996)', 'Forrest Gump (1994)', 'Four Rooms (1995)', 'Four Weddings and a Funeral (1994)', 'Free Willy (1993)', 'Free Willy 2: The Adventure Home (1995)', 'French Twist (Gazon maudit) (1995)', 'Frighteners, The (1996)', 'From Dusk Till Dawn (1996)', 'Fugitive, The (1993)', 'Full Metal Jacket (1987)', 'Full Monty, The (1997)', 'Gattaca (1997)', 'George of the Jungle (1997)', 'Get Shorty (1995)', 'Ghost and the Darkness, The (1996)', 'Glengarry Glen Ross (1992)', 'Godfather, The (1972)', 'Godfather: Part II, The (1974)', 'GoldenEye (1995)', 'Gone with the Wind (1939)', 'Good Will Hunting (1997)', 'Good, The Bad and The Ugly, The (1966)', 'GoodFellas (1990)', 'Graduate, The (1967)', 'Grand Day Out, A (1992)', 'Grosse Pointe Blank (1997)', 'Groundhog Day (1993)', 'Haunted World of Edward D. Wood Jr., The (1995)', 'Heavy Metal (1981)', 'Henry V (1989)', 'Home Alone (1990)', 'Homeward Bound: The Incredible Journey (1993)', 'Hoop Dreams (1994)', 'Horseman on the Roof, The (Hussard sur le toit, Le) (1995)', 'Hot Shots! Part Deux (1993)', 'Hudsucker Proxy, The (1994)', 'Hunt for Red October, The (1990)', 'I.Q. (1994)', 'In the Company of Men (1997)', 'Independence Day (ID4) (1996)', 'Indiana Jones and the Last Crusade (1989)', 'Jaws (1975)', 'Jean de Florette (1986)', 'Jerry Maguire (1996)', 'Jude (1996)', 'Jungle2Jungle (1997)', 'Jurassic Park (1993)', 'Kansas City (1996)', 'Kids in the Hall: Brain Candy (1996)', 'Kolya (1996)', 'Kull the Conqueror (1997)', 'Last of the Mohicans, The (1992)', 'Lawnmower Man, The (1992)', 'Legends of the Fall (1994)', 'Lion King, The (1994)', 'Lone Star (1996)', 'Long Kiss Goodnight, The (1996)', 'Lost World: Jurassic Park, The (1997)', 'Love Bug, The (1969)', 'M*A*S*H (1970)', 'Mad Love (1995)', 'Madness of King George, The (1994)', 'Manon of the Spring (Manon des sources) (1986)', 'Mars Attacks! (1996)', 'Mask, The (1994)', 'Maverick (1994)', 'Maya Lin: A Strong Clear Vision (1994)', 'Men in Black (1997)', 'Mighty Aphrodite (1995)', 'Mimic (1997)', 'Mirror Has Two Faces, The (1996)', 'Moll Flanders (1996)', 'Monty Python and the Holy Grail (1974)', "Monty Python's Life of Brian (1979)", "Mr. Holland's Opus (1995)", 'Mr. Smith Goes to Washington (1939)', 'Much Ado About Nothing (1993)', 'Muppet Treasure Island (1996)', "My Best Friend's Wedding (1997)", 'Mystery Science Theater 3000: The Movie (1996)', 'Nadja (1994)', 'Natural Born Killers (1994)', 'Net, The (1995)', 'Nightmare Before Christmas, The (1993)', 'Nightmare on Elm Street, A (1984)', 'Nikita (La Femme Nikita) (1990)', 'On Golden Pond (1981)', 'Operation Dumbo Drop (1995)', 'Outbreak (1995)', 'Patton (1970)', 'Phenomenon (1996)', 'Pillow Book, The (1995)', 'Pink Floyd - The Wall (1982)', 'Platoon (1986)', 'Postino, Il (1994)', 'Priest (1994)', 'Princess Bride, The (1987)', 'Private Benjamin (1980)', 'Professional, The (1994)', 'Psycho (1960)', 'Pulp Fiction (1994)', 'Quiz Show (1994)', 'Raging Bull (1980)', 'Raiders of the Lost Ark (1981)', 'Raising Arizona (1987)', 'Ref, The (1994)', 'Remains of the Day, The (1993)', 'Reservoir Dogs (1992)', 'Return of the Jedi (1983)', 'Return of the Pink Panther, The (1974)', 'Richard III (1995)', 'Ridicule (1996)', 'Right Stuff, The (1983)', "Robert A. Heinlein's The Puppet Masters (1994)", 'Rock, The (1996)', 'Room with a View, A (1986)', 'Rumble in the Bronx (1995)', 'Santa Clause, The (1994)', 'Searching for Bobby Fischer (1993)', 'Seven (Se7en) (1995)', 'Sgt. Bilko (1996)', 'Shall We Dance? (1996)', 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)', 'Shawshank Redemption, The (1994)', 'Shining, The (1980)', 'Silence of the Lambs, The (1991)', 'Sleeper (1973)', 'Sleepless in Seattle (1993)', 'Sling Blade (1996)', "Smilla's Sense of Snow (1997)", 'Sneakers (1992)', 'Snow White and the Seven Dwarfs (1937)', 'So I Married an Axe Murderer (1993)', 'Sound of Music, The (1965)', 'Spitfire Grill, The (1996)', 'Star Trek III: The Search for Spock (1984)', 'Star Trek IV: The Voyage Home (1986)', 'Star Trek VI: The Undiscovered Country (1991)', 'Star Trek: First Contact (1996)', 'Star Trek: The Wrath of Khan (1982)', 'Star Wars (1977)', 'Stargate (1994)', 'Starship Troopers (1997)', 'Steel (1997)', 'Sting, The (1973)', 'Strange Days (1995)', 'Striptease (1996)', 'Supercop (1992)', 'Swingers (1996)', 'Taxi Driver (1976)', 'Terminator 2: Judgment Day (1991)', 'Terminator, The (1984)', 'Theodore Rex (1995)', 'This Is Spinal Tap (1984)', 'Three Colors: Blue (1993)', 'Three Colors: Red (1994)', 'Three Colors: White (1994)', 'To Wong Foo, Thanks for Everything! Julie Newmar (1995)', 'Top Gun (1986)', 'Toy Story (1995)', 'True Romance (1993)', 'Truth About Cats & Dogs, The (1996)', 'Turbo: A Power Rangers Movie (1997)', 'Twelve Monkeys (1995)', 'Twister (1996)', 'Unbearable Lightness of Being, The (1988)', 'Under Siege (1992)', 'Unforgiven (1992)', 'Unhook the Stars (1996)', 'Usual Suspects, The (1995)', 'Wallace & Gromit: The Best of Aardman Animation (1996)', "Weekend at Bernie's (1989)", 'Welcome to the Dollhouse (1995)', "What's Eating Gilbert Grape (1993)", 'When Harry Met Sally... (1989)', 'When the Cats Away (Chacun cherche son chat) (1996)', 'While You Were Sleeping (1995)', 'White Balloon, The (1995)', 'Willy Wonka and the Chocolate Factory (1971)', 'Wizard of Oz, The (1939)', 'Wrong Trousers, The (1993)', 'Young Frankenstein (1974)', 'Young Guns (1988)', 'unknown']

In [35]:
# Create an item-user matrix (transpose of user-item matrix)
item_user_matrix = user_item_matrix.T

# Calculate item-item similarity using cosine similarity
item_similarity_matrix = cosine_similarity(item_user_matrix)

# Convert to DataFrame for easier handling
item_similarity_df = pd.DataFrame(item_similarity_matrix, index=item_user_matrix.index, columns=item_user_matrix.index)

item_similarity_df.head()

movie_title,'Til There Was You (1997),1-900 (1994),101 Dalmatians (1996),12 Angry Men (1957),187 (1997),2 Days in the Valley (1996),"20,000 Leagues Under the Sea (1954)",2001: A Space Odyssey (1968),3 Ninjas: High Noon At Mega Mountain (1998),"39 Steps, The (1935)",...,Yankee Zulu (1994),Year of the Horse (1997),You So Crazy (1994),Young Frankenstein (1974),Young Guns (1988),Young Guns II (1990),"Young Poisoner's Handbook, The (1995)",Zeus and Roxanne (1997),unknown,Á köldum klaka (Cold Fever) (1994)
movie_title,,,,,,,,,,,,,,,,,,,,,
'Til There Was You (1997),1.000000,0.000000,0.024561,0.099561,0.185236,0.159265,0.000000,0.052203,0.000000,0.033326,...,0.000000,0.000000,0.000000,0.027774,0.118840,0.142315,0.029070,0.000000,0.110208,0.000000
1-900 (1994),0.000000,1.000000,0.014139,0.009294,0.007354,0.004702,0.010055,0.067038,0.000000,0.000000,...,0.152499,0.015484,0.000000,0.069284,0.018243,0.023408,0.006694,0.079640,0.042295,0.000000
101 Dalmatians (1996),0.024561,0.014139,1.000000,0.167006,0.061105,0.143878,0.203781,0.225803,0.027642,0.092337,...,0.000000,0.021965,0.030905,0.274877,0.204267,0.101199,0.056976,0.172155,0.045714,0.000000
12 Angry Men (1957),0.099561,0.009294,0.167006,1.000000,0.056822,0.167235,0.304078,0.422506,0.072682,0.394854,...,0.060946,0.016502,0.000000,0.403270,0.259436,0.145519,0.105226,0.038901,0.060101,0.081261
187 (1997),0.185236,0.007354,0.061105,0.056822,1.000000,0.132327,0.042928,0.065060,0.043133,0.027300,...,0.000000,0.141997,0.000000,0.068257,0.067786,0.091293,0.099490,0.025184,0.142667,0.096449

In [38]:
# Function to recommend items based on item similarity
def recommend_movies_colab_item(user_id, n_recommendations=5):
    # Get the movies watched by the user
    user_ratings = user_item_matrix.loc[user_id]
    watched_movies = user_ratings[user_ratings > 0].index.tolist()

    # Create an empty series to store similarity scores
    movie_scores = pd.Series(dtype=float)

    # Loop through watched movies to calculate similarity scores for other movies
    for movie in watched_movies:
        similar_movies = item_similarity_df[movie]
        movie_scores = movie_scores.add(similar_movies, fill_value=0)

    # Remove already watched movies from recommendations
    movie_scores = movie_scores.drop(labels=watched_movies, errors='ignore')

    # Sort and return top N recommendations
    top_recommendations = movie_scores.sort_values(ascending=False).head(n_recommendations)

    return top_recommendations.index.tolist()

In [39]:
# Recommend movies for user (example for user with ID 1)
collaborative_recommendations_item = recommend_movies_colab_item(1)
collaborative_recommendations_item

['E.T. the Extra-Terrestrial (1982)',
 'Speed (1994)',
 'Batman (1989)',
 'True Lies (1994)',
 'Stand by Me (1986)']

In [40]:
from sklearn.decomposition import TruncatedSVD

# Apply SVD to the user-item matrix
svd = TruncatedSVD(n_components=20)  # Set the number of latent factors
svd_matrix = svd.fit_transform(user_item_matrix)

# Compute the similarity using the SVD-transformed matrix
similarity_matrix = cosine_similarity(svd_matrix)

# Convert to DataFrame for easier handling
similarity_df = pd.DataFrame(similarity_matrix, index=user_item_matrix.index, columns=user_item_matrix.index)

# Rest of the recommendation function remains the same
# Function to recommend movies for a user (only from popular movies)
def recommend_movies_svd(user_id, n_recommendations=5, similarity_threshold=0.5):
    # Get the list of similar users
    similar_users = similarity_df[user_id].sort_values(ascending=False)
    similar_users = similar_users[similar_users > similarity_threshold]

    # Get watched movies for the user
    watched_movies = user_item_matrix.loc[user_id]
    watched_movies = watched_movies[watched_movies > 0].index.tolist()

    # Get movies watched by similar users
    similar_user_ratings = user_item_matrix.loc[similar_users.index]
    similar_user_ratings = similar_user_ratings.mean().sort_values(ascending=False)

    # Recommend movies not yet watched by the user
    recommendations = [movie for movie in similar_user_ratings.index if movie not in watched_movies]

    return recommendations[:n_recommendations]

# Example: Recommend movies for a user (example for user with ID 1)
svd_recommendations = recommend_movies_svd(user_id=1)

svd_recommendations

["Schindler's List (1993)",
 "One Flew Over the Cuckoo's Nest (1975)",
 'E.T. the Extra-Terrestrial (1982)',
 'Casablanca (1942)',
 "It's a Wonderful Life (1946)"]

In [44]:
# ensemble learning
# Combine the results
combined_recommendations = collaborative_recommendations_user + collaborative_recommendations_item + svd_recommendations

["Schindler's List (1993)",
 "One Flew Over the Cuckoo's Nest (1975)",
 'E.T. the Extra-Terrestrial (1982)',
 'Casablanca (1942)',
 "It's a Wonderful Life (1946)",
 'E.T. the Extra-Terrestrial (1982)',
 'Speed (1994)',
 'Batman (1989)',
 'True Lies (1994)',
 'Stand by Me (1986)',
 "Schindler's List (1993)",
 "One Flew Over the Cuckoo's Nest (1975)",
 'E.T. the Extra-Terrestrial (1982)',
 'Casablanca (1942)',
 "It's a Wonderful Life (1946)"]

In [48]:
# Count the frequency of each movie in the combined list
from collections import Counter
recommendation_counts = Counter(combined_recommendations)

# Sort by the most frequent movies (appeared in both recommendations)
ensemble_recommendations = [movie for movie, count in recommendation_counts.most_common()]

# Display the ensemble recommendations
ensemble_recommendations[:5]

['E.T. the Extra-Terrestrial (1982)',
 "Schindler's List (1993)",
 "One Flew Over the Cuckoo's Nest (1975)",
 'Casablanca (1942)',
 "It's a Wonderful Life (1946)"]